/**
******************************************************************************
* @file           : main.c
* @author         : Auto-generated by STM32CubeIDE
* @brief          : Main program body
******************************************************************************
* @attention
*
* Copyright (c) 2025 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/

#include <stdint.h>

int main(void)
{
  RCC_AHB1RSTR_t *ptr_ahb1_clock_register = (RCC_AHB1RSTR_t*)0x40023830;
  GPIOx_MODER_t *ptr_gpiod_mode_register = (GPIOx_MODER_t*)0x40020C00;
  GPIOx_OTYPER_t *ptr_gpiod_output_data_register = (GPIOx_OTYPER_t*)0x40020C14;
  
  ptr_ahb_clock_enable->gpiod_en=1;
  
  ptr_gpiod_mode_register->pin_12=1;
  
  while(1) {
    // setting 12th bit as HIGH
    ptr_gpiod_output_data_register->pin_12 = 1;
    // looping, just taking time
    for (uint32_t i = 0; i < 30000; i++);
    // clear out the bit to set it to LOW
    ptr_gpiod_output_data_register->pin_12 = 0;
    for (uint32_t i = 0; i < 30000; i++);
  }
}
